In [1]:
# Gauss-Seidel Iteration (interactive class session)

In [2]:
import numpy as np

In [3]:
tol = 1.0e-8

In [4]:
# Set up A
A = np.array([
[4, -1, 0, 0, 0],
[-1, 4, -1, 0, 0],
[0, -1, 4, -1, 0],
[0,0,-1,4,-1],
[0,0,0,-1,4],
])
A

array([[ 4, -1,  0,  0,  0],
       [-1,  4, -1,  0,  0],
       [ 0, -1,  4, -1,  0],
       [ 0,  0, -1,  4, -1],
       [ 0,  0,  0, -1,  4]])

In [5]:
# set up d
d= np.array ([3,2,2,2,3], dtype=float)
d

array([3., 2., 2., 2., 3.])

In [9]:
# initialize x
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [10]:
# define max number of sweeps
nsweep = 20

In [11]:
for k in range(nsweep):
    x_old = x.copy()
    for i in range(5):
        sigma = 0.0
        for j in range(5):
            if j!=i:
                sigma = sigma + A[i,j]*x[j]
        x[i] = (d[i] - sigma)/A[i,i]
    residual = np.linalg.norm(x-x_old)
    if residual < tol:
        break


print(x)
print(residual)
        


[1. 1. 1. 1. 1.]
3.1053590845414103e-09
