# Companion Notebook: Solving Linear Systems

This notebook accompanies **Lecture 3: Solving Linear Systems**.

The goal is to reinforce how engineers solve linear systems of the form
\begin{equation}
A\mathbf{x} = \mathbf{b}
\end{equation}
using numerical software, and to understand why computing the matrix inverse
is generally discouraged in practice.

This notebook is exploratory and instructional — it is not graded.

## A simple linear system

We begin with a small linear system:
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix},
\qquad
\mathbf{b} =
\begin{bmatrix}
9 \\
8
\end{bmatrix}.
\end{equation}

We will solve this system in several different ways and compare the results.

In [9]:
import numpy as np

A = np.array([[1.0, 2.0],
              [3.0, 4.0]])

b = np.array([9.0, 8.0])

In [10]:
A,b

(array([[1., 2.],
        [3., 4.]]),
 array([9., 8.]))

## Matrix multiplication
### Number of rows in $A$ need to be equal to the number of columns in $b$

In [11]:
A@b

array([25., 59.])

In [12]:
np.dot(A, b)

array([25., 59.])

In [13]:
np.dot(b,A)

array([33., 50.])

In [14]:
b@A

array([33., 50.])

In [15]:
A.T@b

array([33., 50.])

## Solving the system using `np.linalg.solve`

The recommended way to solve a linear system in Python is to use
`np.linalg.solve`. This function solves the system directly without
forming the matrix inverse.

In [17]:
x = np.linalg.solve(A, b)
x

array([-10. ,   9.5])

## Solving using the matrix inverse (not recommended)

From linear algebra, we know that the formal solution can be written as
\[
\mathbf{x} = A^{-1}\mathbf{b}.
\]

We compute this solution only for comparison.

In [18]:
Ainv = np.linalg.inv(A)
x_inv = Ainv @ b

x_inv

array([-10. ,   9.5])

## Comparison

The two solutions appear identical (up to roundoff). However, computing
the inverse:
- is more expensive,
- is less numerically stable,
- and is unnecessary.

This is why professional engineering codes never form matrix inverses
explicitly.

## Checking the residual

A good way to assess a solution is to compute the residual:
\[
\mathbf{r} = A\mathbf{x} - \mathbf{b}.
\]

A good solution should have a small residual norm.

In [19]:
r = A @ x - b
residual_norm = np.linalg.norm(r)

r, residual_norm

(array([0., 0.]), np.float64(0.0))

## Conditioning matters

Even when using a correct algorithm, the accuracy of the solution depends
on the conditioning of the matrix \(A\).

In the previous lecture, we saw that some matrices (such as the Hilbert
matrix) are extremely sensitive to numerical error.

In the next lecture, we will explore conditioning and accuracy in more detail.

In [20]:
np.linalg.cond(A)

np.float64(14.933034373659263)

In [22]:
pip install scipy

  Using cached scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
Using cached scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl (30.3 MB)
Note: you may need to restart the kernel to use updated packages.


In [23]:
from scipy.linalg import hilbert
A = hilbert(5)
np.linalg.cond(A)

np.float64(476607.25024265185)