In [1]:
import numpy as np

In [2]:
x = np.array([1,3,5,7])
x

array([1, 3, 5, 7])

In [3]:
x[1:3]

array([3, 5])

In [4]:
x[::2]

array([1, 5])

In [7]:
n=5
for i in range(1,n+1):
    isquared = i*i
    print(isquared)


1
4
9
16
25


In [11]:
number = 0
if number > 0:
    print('number is positive')
elif number < 0:
    print('number is negative')
else:
    print('number is zero')

    

number is zero


In [17]:
# Set up numpy arrays A and x
A=np.array([[2,-1,-2],[-1,2,-1],[-2,0,2]])
x=np.array([1,2,3])
b = np.zeros(3)
# suppose A is of order mxm and x is mx1
m = len(A)
for i in range(m):
    b[i]=0
    for j in range(m):
        b[i] = b[i]+A[i,j]*x[j]

In [18]:
b

array([-6.,  0.,  4.])

In [24]:
niter = 1
tol = 1.e-12
xi=1
for i in range(niter):
    fi = xi**2-2
    fpi = 2*xi
    dxi = -fi/fpi
    xi = xi+dxi
print(xi)

1.5
